# Change these first
owner: cero-pirani # Your GitHub organization or username, where this repository lives
repo: Pirani-status-upptime # The name of this repository

sites:
  - name: Pirani Freemium - Service organizations - QA
    url: https://cert.pirani.co/services/organizations/actuator/health
    method: GET
  - name: Pirani Freemium - Service organizations
    url: https://platform.pirani.co/services/organizations/actuator/health
    method: GET
  - name: Pirani Freemium - WEBSITE
    url: https://www.piranirisk.com
  - name: Google
    url: https://www.google.com
    
assignees:
  - josevargas94

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: cero-pirani.github.io
  baseUrl: /Pirani-status-upptime
  logoUrl: https://www.piranirisk.com/hs-fs/hubfs/logo/logo_pirani_img.png?width=150&name=logo_pirani_img.png
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pirani Status
  introTitle: "**Pirani Status Web** is the monitor and status page."
  introMessage: WebStatus Pirani
  navbar:
    - title: Status
      href: /Pirani-status-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
